# Generated by Django 4.1.6 on 2023-02-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('profundo', 'Profundo'), ('simples', 'Simples')], max_length=30)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
