# Generated by Django 4.1.6 on 2023-02-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='categoria',
            field=models.CharField(choices=[('Profundo', 'Profundo'), ('Simples', 'Simples')], max_length=30),
        ),
    ]
