# Generated by Django 4.1.6 on 2023-02-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('gerente', 'Gerente'), ('atendente', 'Atendente'), ('helper', 'Helper')], max_length=50)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
    ]
