# Generated by Django 4.1.6 on 2023-02-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('atendente', 'Atendente'), ('helper', 'Helper')], max_length=50),
        ),
    ]
