# Generated by Django 4.1.6 on 2023-02-19 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
        ('cliente', '0001_initial'),
        ('servico', '0001_initial'),
        ('atendimento', '0002_alter_atendimento_atendente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='atendente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='funcionarios', to='funcionario.funcionario'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='helper',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='funcionarios_helper', to='funcionario.funcionario'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='servico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='servico.servico'),
        ),
    ]
