# Generated by Django 4.1.6 on 2023-02-20 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_alter_funcionario_cargo'),
        ('atendimento', '0006_alter_atendimento_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='atendente',
            field=models.ForeignKey(blank=True, default='Site', on_delete=django.db.models.deletion.DO_NOTHING, related_name='atendimentos', to='funcionario.funcionario'),
        ),
    ]
